version: '3'
services: 
  web: 
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    db:
      image: postgres
      environment:
        - POSTGRES_USER: example
        - POSTGRES_PASSWORD: Aa123456
        - POSTGRES_DB: myapp
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: